print("hello world!")
print(5+3)
print("python","is","fun!")
print("she said,\"Hello!\"")
print("first line\nSecond line")
print("Item 1\Item2\Item3")
print("The result is",42)
print(12345)
print(3.14159)
print("Dollar sign:$")
print("apple","banana","cherry",sep=",")
print("Hello,",end="")
print("World!")
print("Python!"*3)
print("\u2764")
print()
print("Hello"+"world!")
print(True)
print(False)
print(1.2e3)
print("""This is a multiline 
      print statement.""")
print("This is a backlash:\\")